
menu:
  main:
    - identifier: home
      name: ホーム
      url: /
      weight: 1
    - identifier: about
      name: このサイトについて
      url: /pages/about/
      weight: 2
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 3
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 4
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 5
params:
  abbrDateFmt: "Jan 2"
  author: "山田ハヤオ"
  brandIconFile: "images/brandIcon.svg"
  dateFmt: "2006-01-02"
#  customStylesheets: # Use to override theme styles, like logo size
#    - "css/custom.css"
  social:
    - name: GitHub
      url: https://github.com/Hayao0819
    - name: GitLab
      url: https://gitlab.com/Hayao0819
    - name: Twitter
      url: https://twitter.com/Hayao0819
    - name: Reddit
      url: https://www.reddit.com/user/Hayao0819
  subtitle: "山田ハヤオについて"
